export const appFonts = {
  Q: require("../../assets/fonts/quicksand-400.ttf"),
  QMedium: require("../../assets/fonts/quicksand-500.ttf"),
  QSemi: require("../../assets/fonts/quicksand-600.ttf"),
  QBold: require("../../assets/fonts/quicksand-700.ttf"),
  CVInter: require("../../assets/fonts/inter-400.ttf"),
  CVInterBold: require("../../assets/fonts/inter-700.ttf"),
  CVSource: require("../../assets/fonts/source-400.ttf"),
  CVSourceBold: require("../../assets/fonts/source-700.ttf"),
  CVLora: require("../../assets/fonts/lora-400.ttf"),
  CVLoraBold: require("../../assets/fonts/lora-700.ttf"),
  CVGaramond: require("../../assets/fonts/garamond-400.ttf"),
  CVGaramondBold: require("../../assets/fonts/garamond-700.ttf"),
  CVRoboto: require("../../assets/fonts/roboto-400.ttf"),
  CVRobotoBold: require("../../assets/fonts/roboto-700.ttf"),
  CVOpenSans: require("../../assets/fonts/opensans-400.ttf"),
  CVOpenSansBold: require("../../assets/fonts/opensans-700.ttf"),
  CVMerriweather: require("../../assets/fonts/merriweather-400.ttf"),
  CVMerriweatherBold: require("../../assets/fonts/merriweather-700.ttf"),
  CVBaskerville: require("../../assets/fonts/baskerville-400.ttf"),
  CVBaskervilleBold: require("../../assets/fonts/baskerville-700.ttf"),
  CVNoto: require("../../assets/fonts/noto-400.ttf"),
  CVNotoBold: require("../../assets/fonts/noto-700.ttf"),
  CVDM: require("../../assets/fonts/dm-400.ttf"),
  CVDMBold: require("../../assets/fonts/dm-700.ttf"),
};
